info:
  name: Update application
  type: http
  seq: 13

http:
  method: PUT
  url: "{{host}}/api/applications/{{id}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
